language: swift
osx_image: xcode12
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE="Moments.xcworkspace"
    - APP_SCHEME="Moments"
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro Max" APP_SCHEME=${APP_SCHEME}
before_install:
  - bundle install
  - bundle exec pod install
  
jobs:
  include:
    # - stage: "Build"
    #  name: "Build AppStore app"
    #  script:
    #    - set -o pipefail
    #    - ls # will remove  
      # - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$APP_SCHEME" -destination "$DESTINATION" -configuration AppStore | xcpretty;

    - stage: "Test"
      name: "Test app"
      script:
        - set -o pipefail
        - bundle exec fastlane tests
  
    - stage: "Archive, sign and deploy internal app"
      name: "Archive Internal app"
      script:
        - set -o pipefail
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane download_profiles
        - ./scripts/increment_build_number.sh
        - bundle exec fastlane archive_internal
        - bundle exec fastlane upload_symbols_to_crashlytics_internal
        - bundle exec fastlane deploy_internal
    
    - stage: "Archive, sign and deploy production app"
      name: "Archive Production app"
      script:
        - set -o pipefail
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane download_profiles
        - ./scripts/increment_build_number.sh
        - bundle exec fastlane archive_appstore
        - bundle exec fastlane upload_symbols_to_crashlytics_appstore
        - bundle exec fastlane deploy_appstore

after_success:
  - sleep 5 # Workaround for https://github.com/travis-ci/travis-ci/issues/4725